targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/model/entity/{{}}.dart': 'lib/model/entity/generated/{{}}.g.dart'
      freezed:
        options:
          build_extensions:
            '^lib/model/entity/{{}}.dart': 'lib/model/entity/generated/{{}}.freezed.dart'